#!/usr/bin/env python3
import json
import plistlib
import sys
from pathlib import Path

if len(sys.argv) != 4:
    raise SystemExit('Usage: generate_firebase_options.py ANDROID_JSON IOS_PLIST OUTPUT_DART')

android_path, ios_path, out_path = map(Path, sys.argv[1:])
android = json.loads(android_path.read_text())
with ios_path.open('rb') as f:
    ios = plistlib.load(f)

project_info = android['project_info']
clients = android['client']
client = next((c for c in clients if c.get('client_info', {}).get('android_client_info', {}).get('package_name') == 'com.example.food_app_mvp'), clients[0])
client_info = client['client_info']
api_key = client['api_key'][0]['current_key']
android_app_id = client_info['mobilesdk_app_id']
sender_id = str(project_info['project_number'])
project_id = project_info['project_id']

def dart(value):
    return "'" + str(value).replace('\\', '\\\\').replace("'", "\\'") + "'"

content = f'''import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart';

/// Generated by scripts/generate_firebase_options.py from the registered
/// Firebase Android and iOS app configurations.
class DefaultFirebaseOptions {{
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: {dart(api_key)},
    appId: {dart(android_app_id)},
    messagingSenderId: {dart(sender_id)},
    projectId: {dart(project_id)},
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: {dart(ios['API_KEY'])},
    appId: {dart(ios['GOOGLE_APP_ID'])},
    messagingSenderId: {dart(ios['GCM_SENDER_ID'])},
    projectId: {dart(project_id)},
    iosBundleId: {dart(ios.get('BUNDLE_ID', 'com.example.foodAppMvp'))},
  );

  static FirebaseOptions get currentPlatform {{
    switch (defaultTargetPlatform) {{
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Firebase Push ist für diese Plattform nicht konfiguriert.');
    }}
  }}
}}
'''
out_path.write_text(content)
