create schema if not exists extensions;
create extension if not exists postgis with schema extensions;

create table if not exists public.restaurant_index (
  id bigint generated by default as identity primary key,
  dedupe_key text not null unique,
  name text not null,
  address text,
  city text,
  area text not null check (area in ('lorsch_20km', 'pforzheim_20km')),
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  location extensions.geography(Point, 4326) not null,
  cuisine text[] not null default '{}',
  categories text[] not null default '{}',
  phone text,
  website text,
  order_url text,
  opening_hours text,
  delivery_available boolean not null default false,
  source_ids jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists restaurant_index_location_gist
  on public.restaurant_index using gist (location);
create index if not exists restaurant_index_cuisine_gin
  on public.restaurant_index using gin (cuisine);
create index if not exists restaurant_index_area_idx
  on public.restaurant_index (area);

alter table public.restaurant_index enable row level security;
drop policy if exists "authenticated can read restaurant index" on public.restaurant_index;
create policy "authenticated can read restaurant index"
  on public.restaurant_index for select to authenticated using (true);
grant select on public.restaurant_index to authenticated;

create or replace function public.search_restaurants(
  p_lat double precision,
  p_lon double precision,
  p_cuisine text,
  p_delivery_only boolean default false,
  p_limit integer default 10,
  p_radius_km double precision default 10
)
returns table (
  id text,
  name text,
  address text,
  city text,
  distance_km double precision,
  latitude double precision,
  longitude double precision,
  phone text,
  website text,
  order_url text,
  opening_hours text,
  delivery_available boolean,
  cuisine text
)
language sql
stable
set search_path = public, extensions
as $$
  with requested as (
    select case p_cuisine
      when 'Italienisch' then array['italian']::text[]
      when 'Griechisch' then array['greek']::text[]
      when 'Asiatisch' then array['asian','chinese','thai','vietnamese','korean','indonesian','malaysian']::text[]
      when 'Indisch' then array['indian']::text[]
      when 'Burger' then array['burger']::text[]
      when 'Mexikanisch' then array['mexican']::text[]
      when 'Vegetarisch' then array['vegetarian','vegan']::text[]
      when 'Sushi' then array['sushi']::text[]
      when 'Pizza' then array['pizza','italian_pizza']::text[]
      when 'Döner' then array['kebab','doner','döner']::text[]
      when 'Steak' then array['steak','steak_house']::text[]
      else array[]::text[]
    end as values
  ),
  origin as (
    select extensions.st_setsrid(
      extensions.st_makepoint(p_lon, p_lat), 4326
    )::extensions.geography as point
  )
  select
    r.id::text,
    r.name,
    r.address,
    r.city,
    round((extensions.st_distance(r.location, o.point) / 1000.0)::numeric, 2)::double precision as distance_km,
    r.latitude,
    r.longitude,
    r.phone,
    r.website,
    r.order_url,
    r.opening_hours,
    r.delivery_available,
    nullif(array_to_string(r.cuisine, ';'), '') as cuisine
  from public.restaurant_index r
  cross join origin o
  cross join requested q
  where extensions.st_dwithin(r.location, o.point, greatest(0, p_radius_km) * 1000.0)
    and (p_cuisine = 'Überrasch mich' or r.cuisine && q.values)
    and (not p_delivery_only or r.delivery_available)
  order by extensions.st_distance(r.location, o.point), r.id
  limit least(greatest(p_limit, 1), 50);
$$;

grant execute on function public.search_restaurants(double precision, double precision, text, boolean, integer, double precision) to authenticated;
