-- V1.0 security hardening
-- 1) Rate-limit AI recipe generation per authenticated user.
-- 2) Make all public SECURITY DEFINER functions use a fixed search_path.
-- 3) Prevent anonymous/public direct EXECUTE on SECURITY DEFINER functions.

create table if not exists public.ai_generation_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists ai_generation_events_user_created_at_idx
  on public.ai_generation_events (user_id, created_at desc);

alter table public.ai_generation_events enable row level security;

revoke all on public.ai_generation_events from public, anon, authenticated;

create or replace function public.consume_ai_generation_quota(
  p_hourly_limit integer default 5,
  p_daily_limit integer default 20
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  hourly_count integer;
  daily_count integer;
begin
  if uid is null then
    raise exception 'Nicht authentifiziert.' using errcode = '28000';
  end if;

  if p_hourly_limit < 1 or p_daily_limit < 1 then
    raise exception 'Ungültige Rate-Limit-Konfiguration.' using errcode = '22023';
  end if;

  -- Serialize quota consumption for the same user so concurrent requests
  -- cannot bypass the limit between COUNT and INSERT.
  perform pg_advisory_xact_lock(hashtextextended(uid::text, 0));

  -- Opportunistically prune only this user's old events. This keeps the table
  -- bounded without requiring a privileged client-side cleanup job.
  delete from public.ai_generation_events
  where user_id = uid
    and created_at < now() - interval '30 days';

  select count(*) into hourly_count
  from public.ai_generation_events
  where user_id = uid
    and created_at >= now() - interval '1 hour';

  if hourly_count >= p_hourly_limit then
    raise exception 'KI-Limit erreicht. Bitte später erneut versuchen.'
      using errcode = 'P0001';
  end if;

  select count(*) into daily_count
  from public.ai_generation_events
  where user_id = uid
    and created_at >= now() - interval '24 hours';

  if daily_count >= p_daily_limit then
    raise exception 'Tageslimit für KI-Rezeptvorschläge erreicht.'
      using errcode = 'P0001';
  end if;

  insert into public.ai_generation_events(user_id) values (uid);
  return true;
end;
$$;

revoke all on function public.consume_ai_generation_quota(integer, integer) from public, anon;
grant execute on function public.consume_ai_generation_quota(integer, integer) to authenticated;

-- Defense in depth for every existing public SECURITY DEFINER routine.
-- Trigger-owned functions do not require EXECUTE privileges from clients, but
-- granting authenticated keeps legitimate RPC entry points callable.
do $$
declare
  r record;
begin
  for r in
    select p.oid,
           n.nspname as schema_name,
           p.proname,
           pg_get_function_identity_arguments(p.oid) as args
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.prosecdef = true
  loop
    execute format(
      'alter function %I.%I(%s) set search_path = public',
      r.schema_name, r.proname, r.args
    );
    execute format(
      'revoke execute on function %I.%I(%s) from public, anon',
      r.schema_name, r.proname, r.args
    );
    execute format(
      'grant execute on function %I.%I(%s) to authenticated',
      r.schema_name, r.proname, r.args
    );
  end loop;
end $$;
