-- Expand the standard onboarding catalog with additional meat, fish and vegetable options.
-- ON CONFLICT DO NOTHING keeps this safe to re-run against databases with partially seeded catalogs.
insert into public.foods (id, name, category, default_unit) values
  ('beef_tenderloin', 'Rinderfilet', 'Fleisch', 'g'),
  ('beef_roast', 'Rinderbraten', 'Fleisch', 'g'),
  ('mixed_minced_meat', 'Gemischtes Hackfleisch', 'Fleisch', 'g'),
  ('lamb_chops', 'Lammkotelett', 'Fleisch', 'g'),
  ('lamb_minced_meat', 'Lammhackfleisch', 'Fleisch', 'g'),
  ('duck_breast', 'Entenbrust', 'Fleisch', 'g'),
  ('chicken_wings', 'Hähnchenflügel', 'Fleisch', 'Stück'),
  ('chicken_minced_meat', 'Hähnchenhackfleisch', 'Fleisch', 'g'),
  ('pork_roast', 'Schweinebraten', 'Fleisch', 'g'),
  ('pork_ribs', 'Spareribs', 'Fleisch', 'g'),
  ('mackerel', 'Makrele', 'Fisch', 'g'),
  ('herring', 'Hering', 'Fisch', 'g'),
  ('halibut', 'Heilbutt', 'Fisch', 'g'),
  ('redfish', 'Rotbarsch', 'Fisch', 'g'),
  ('sea_bream', 'Dorade', 'Fisch', 'g'),
  ('sea_bass', 'Wolfsbarsch', 'Fisch', 'g'),
  ('pangasius', 'Pangasius', 'Fisch', 'g'),
  ('squid', 'Tintenfisch', 'Fisch', 'g'),
  ('mussels', 'Miesmuscheln', 'Fisch', 'g'),
  ('fennel', 'Fenchel', 'Gemüse', 'Stück'),
  ('radish', 'Radieschen', 'Gemüse', 'g'),
  ('beetroot', 'Rote Bete', 'Gemüse', 'g'),
  ('parsnip', 'Pastinake', 'Gemüse', 'g'),
  ('parsley_root', 'Petersilienwurzel', 'Gemüse', 'g'),
  ('pak_choi', 'Pak Choi', 'Gemüse', 'g'),
  ('chinese_cabbage', 'Chinakohl', 'Gemüse', 'g'),
  ('white_cabbage', 'Weißkohl', 'Gemüse', 'g'),
  ('pointed_cabbage', 'Spitzkohl', 'Gemüse', 'g'),
  ('chard', 'Mangold', 'Gemüse', 'g'),
  ('endive', 'Endivie', 'Gemüse', 'g'),
  ('chicory', 'Chicorée', 'Gemüse', 'g'),
  ('artichoke', 'Artischocke', 'Gemüse', 'Stück'),
  ('okra', 'Okra', 'Gemüse', 'g'),
  ('sweet_potato', 'Süßkartoffel', 'Gemüse', 'g'),
  ('kohlrabi', 'Kohlrabi', 'Gemüse', 'Stück'),
  ('radish_root', 'Rettich', 'Gemüse', 'Stück'),
  ('spring_onion', 'Frühlingszwiebel', 'Gemüse', 'Bund'),
  ('shallot', 'Schalotte', 'Gemüse', 'Stück'),
  ('sugar_snap_peas', 'Zuckerschoten', 'Gemüse', 'g'),
  ('romanesco', 'Romanesco', 'Gemüse', 'g'),
  ('cherry_tomatoes', 'Cherrytomaten', 'Gemüse', 'g'),
  ('red_chili_pepper', 'Frische Chilischote', 'Gemüse', 'Stück'),
  ('watercress', 'Brunnenkresse', 'Gemüse', 'g'),
  ('corn_salad', 'Feldsalat', 'Gemüse', 'g'),
  ('swiss_chard', 'Mangoldblätter', 'Gemüse', 'g')
on conflict do nothing;
